# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataProcess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataProcess(object):
    def setupUi(self, DataProcess):
        DataProcess.setObjectName("DataProcess")
        DataProcess.resize(808, 512)
        self.toolButton = QtWidgets.QToolButton(DataProcess)
        self.toolButton.setGeometry(QtCore.QRect(770, 10, 21, 31))
        self.toolButton.setObjectName("toolButton")
        self.label = QtWidgets.QLabel(DataProcess)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.ShowFilePath = QtWidgets.QTextEdit(DataProcess)
        self.ShowFilePath.setGeometry(QtCore.QRect(80, 10, 681, 31))
        self.ShowFilePath.setObjectName("ShowFilePath")
        self.pushButton = QtWidgets.QPushButton(DataProcess)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.listView = QtWidgets.QListView(DataProcess)
        self.listView.setGeometry(QtCore.QRect(10, 120, 121, 381))
        self.listView.setObjectName("listView")
        self.Showlog = QtWidgets.QTextEdit(DataProcess)
        self.Showlog.setGeometry(QtCore.QRect(320, 120, 481, 381))
        self.Showlog.setObjectName("Showlog")
        self.groupBox = QtWidgets.QGroupBox(DataProcess)
        self.groupBox.setGeometry(QtCore.QRect(140, 120, 171, 381))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 50, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 100, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 150, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 200, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 250, 101, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_2 = QtWidgets.QGroupBox(DataProcess)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 50, 481, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(DataProcess)
        self.toolButton.clicked.connect(DataProcess.OpenFile)
        self.pushButton.clicked.connect(DataProcess.load_data)
        self.listView.activated['QModelIndex'].connect(DataProcess.choose_index)
        self.pushButton_2.clicked.connect(DataProcess.jingjiCls)
        self.pushButton_3.clicked.connect(DataProcess.allmoney)
        self.pushButton_4.clicked.connect(DataProcess.barfig)
        self.pushButton_5.clicked.connect(DataProcess.words_freq)
        self.pushButton_6.clicked.connect(DataProcess.wordscloud)
        self.pushButton_7.clicked.connect(DataProcess.school_freq)
        self.pushButton_8.clicked.connect(DataProcess.school_money)
        QtCore.QMetaObject.connectSlotsByName(DataProcess)

    def retranslateUi(self, DataProcess):
        _translate = QtCore.QCoreApplication.translate
        DataProcess.setWindowTitle(_translate("DataProcess", "Form"))
        self.toolButton.setText(_translate("DataProcess", "..."))
        self.label.setText(_translate("DataProcess", "导入文件"))
        self.pushButton.setText(_translate("DataProcess", "导入数据"))
        self.groupBox.setTitle(_translate("DataProcess", "单样本分析"))
        self.pushButton_2.setText(_translate("DataProcess", "经济分类总览"))
        self.pushButton_3.setText(_translate("DataProcess", "申请金额总览"))
        self.pushButton_4.setText(_translate("DataProcess", "饼状图分析"))
        self.pushButton_5.setText(_translate("DataProcess", "词频分析"))
        self.pushButton_6.setText(_translate("DataProcess", "词云分析"))
        self.groupBox_2.setTitle(_translate("DataProcess", "整体分析"))
        self.pushButton_7.setText(_translate("DataProcess", "申请频率"))
        self.pushButton_8.setText(_translate("DataProcess", "申请金额"))
